version: "3.2"
services:
  ocr:
    image: apex-ocr-common
    network_mode: "host"
    environment:
    - DISPLAY
    volumes:
      - ./data:/home/apex/apex-ocr/data
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]