version: "3.2"
services:
  ocr:
    image: apex_ocr
    network_mode: "host"
    environment:
    - DISPLAY
    volumes:
      - ./data:/home/apex/apex-ocr/data
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /run/user/1001/pulse:/run/user/1001/pulse:ro
      - $HOME/.config/pulse:/usr/src/app/.config/pulse
    devices:
      - /dev/snd
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]